# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

# Install system dependencies if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install uv which is required for running the server.
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir uv

# Copy project files into the container
WORKDIR /app
COPY . /app

# Install project dependencies
RUN pip install --no-cache-dir .

# Expose port if needed (optional, since MCP servers typically use stdio, but uv might open HTTP interfaces)
EXPOSE 5173

# Command to run the MCP server
ENTRYPOINT ["uv", "run", "--with", "mcp-doris", "--python", "3.13", "mcp-doris"]
